import { Router, type IRouter } from "express";
import healthRouter from "./health";
import crewRouter from "./crew";
import jobsRouter from "./jobs";
import tasksRouter from "./tasks";
import messagesRouter from "./messages";
import photosRouter from "./photos";
import equipmentRouter from "./equipment";
import dashboardRouter from "./dashboard";
import locationsRouter from "./locations";
import timeOffRouter from "./time-off";
import crewDocumentsRouter from "./crew-documents";
import notificationsRouter from "./notifications";
import timeEntriesRouter from "./time-entries";
import jobContactsRouter from "./job-contacts";
import sideQuestsRouter from "./side-quests";
import employeeRequestsRouter from "./employee-requests";
import jobFormsRouter from "./job-forms";

const router: IRouter = Router();

router.use(healthRouter);
router.use(notificationsRouter);
router.use(timeEntriesRouter);
router.use(jobContactsRouter);
router.use(crewRouter);
router.use(locationsRouter);
router.use(timeOffRouter);
router.use(crewDocumentsRouter);
router.use(jobsRouter);
router.use(tasksRouter);
router.use(messagesRouter);
router.use(photosRouter);
router.use(equipmentRouter);
router.use(dashboardRouter);
router.use(sideQuestsRouter);
router.use(employeeRequestsRouter);
router.use(jobFormsRouter);

export default router;
