// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/app-store/AppStoreListing.tsx": () => import("../components/mockups/app-store/AppStoreListing.tsx")
};
